Feat: endpoint to check if form belongs to workspace
grindery-io/grindery-wallet-api pull request #5
Opened 2024-02-07 21:36 UTC by juniormp

2024-02-07 23:43 UTC, milukove requested changes

2024-02-07 23:43 UTC, milukove commented on src/routes/v2/form.ts
> + * GET /v2/contacts/:id
Should be `GET /v2/form/{id}`

2024-02-07 23:43 UTC, milukove commented on src/routes/v2/form.ts
> +    const response = await axios.get(`https://api.typeform.com/forms/${id}`);
It doesn't require any API key?

2024-02-08 12:05 UTC, juniormp commented on src/routes/v2/form.ts
> +    const response = await axios.get(`https://api.typeform.com/forms/${id}`);
@milukove know, Its an opening endpoint.

2024-02-08 18:39 UTC, milukove approved these changes

2024-02-08 18:39 UTC, merged